name: Build Geode Mod

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Android
        uses: geode-sdk/build-geode-mod@v1
        with:
          target: Android
          combine: true
          sdk: nightly

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Neverlose-Android
          path: build/*.geode
